export const ErrorCodes = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  SHIFT_LOGOUT_REQUIRED: 'SHIFT_LOGOUT_REQUIRED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  MQTT_UNAVAILABLE: 'MQTT_UNAVAILABLE',
  RASPI_OFFLINE: 'RASPI_OFFLINE',
  CPK_UNAVAILABLE: 'CPK_UNAVAILABLE',
  PDSERVICE_UNAVAILABLE: 'PDSERVICE_UNAVAILABLE',
  NETWORK_ERROR: 'NETWORK_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
